
trigger:
  branches:
    include:
      - main  # Trigger on main branch (adjust as necessary)

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu VM for running the pipeline

variables:
  # Define SonarCloud variables (adjust these values)
  SONAR_PROJECT_KEY: 'javatest01'  # Replace with your SonarCloud project key
  SONAR_ORG: 'javatest'  # Replace with your SonarCloud organization key
  SONAR_TOKEN: $(SonarCloudToken)  # SonarCloud token stored as pipeline secret
  
steps:
  # Step 1: Set up Java environment
  - task: JavaToolInstaller@0
    inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

  # Step 2: Install dependencies using Maven
  - script: mvn clean install -DskipTests=true
    displayName: 'Maven Clean and Install (skip tests for faster build)'

  # Step 3: Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud'  # Use SonarCloud service connection configured in Azure DevOps
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: $(SONAR_PROJECT_KEY)
      cliProjectName: 'javaproject'
      cliSources: '.'
      extraProperties: |
        sonar.sources=module-without-tests/src/main/java,module-with-tests/src/main/java  # Define source folders
        sonar.tests=module-with-tests/src/test/java  # Define test folders
        sonar.java.binaries=module-without-tests/target/module-with-tests/target  # Define binary folders for analysis
        sonar.junit.reportPaths=module-with-tests/target/test-classes  # Path to JUnit test results (can be adjusted)
        sonar.jacoco.reportPaths=module-with-tests/target/site/jacoco/jacoco.xml  # Path to JaCoCo coverage report

  # Step 4: Run SonarCloud Analysis
  - script: mvn sonar:sonar -Dsonar.login=$(SONAR_TOKEN)
    displayName: 'Run SonarCloud Analysis'

  # Step 5: Post-analysis step (optional, e.g., if you want to add notifications, etc.)
  - script: echo "SonarCloud Analysis Completed!"
    displayName: 'SonarCloud Analysis Finished'
