trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
  #SONAR_PROJECT_KEY: 'javatest01'  # Replace with your SonarCloud project key
  SONAR_ORG: 'javatest'  # Replace with your SonarCloud organization key
  SONAR_TOKEN: $(SonarCloudToken)  # SonarCloud token stored as pipeline secret

steps:
  - task: JavaToolInstaller@0
    inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-B -DskipTests'
      publishJUnitResults: false
      goals: 'clean install'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-B'
      goals: 'verify'
      codeCoverageTool: 'JaCoCo'
      
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'artifact'
      publishLocation: 'pipeline'


  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'sonarcloud'
      organization: 'javatest'  # Use SonarCloud service connection configured in Azure DevOps
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'javatest01'
      cliProjectName: 'javatest'
      cliSources: '.'

  - task: SonarCloudAnalyze@3

  - task: SonarCloudPublish@3
